[
 {
   "state_long": "Oklahoma",
   "state_short": "OK",
   "state_num": "46",
   "state_ratified_year": 1907,
   "title": "True Grit",
   "author": "Charles Portis",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4546176",
   "img": "img/true_grit.jpg",
   "published": "1968",
   "pagecount": "215",
   "average_rating": "N/A",
   "description": "A classic Western novel set in the rugged landscape of the Indian Territory, now known as Oklahoma. The determined Mattie Ross seeks justice for her father's murder. With the help of the rough U.S. Marshal Rooster Cogburn, they embark on a perilous journey to track down the outlaw Tom Chaney.",
   "url": "https://www.goodreads.com/search?q=True+Grit"
 },
 {
   "state_long": "Pennsylvania",
   "state_short": "PN",
   "state_num": "2",
   "state_ratified_year": 1787,
   "title": "The Killer Angels",
   "author": "Michael Shaara",
   "audiobook_url": "",
   "img": "img/the_killer_angels.jpg",
   "published": "1975",
   "pagecount": "402",
   "average_rating": "N/A",
   "description": "A novel based on the action Battle of Gettysburg.",
   "url": "https://www.goodreads.com/search?q=The+Killer+Angels"
 },
 {
   "state_long": "Florida",
   "state_short": "FL",
   "state_num": "27",
   "state_ratified_year": 1845,
   "title": "Their Eyes Were Watching God",
   "author": "Zora Neale Hurston",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Their%20Eyes%20Were%20Watching%20God",
   "img": "img/their_eyes_were_watching_god.jpg",
   "published": "1978",
   "pagecount": "306",
   "average_rating": "N/A",
   "description": "Initially published in 1937, this novel about a proud, independent black woman has, since its reissue in trade paper in 1978, been the most widely readand highly acclaimed novel in the canon of African-American literature. With this richly illustrated new edition, the novel is finally accorded the treatment it deserves as a classic.",
   "url": "https://www.goodreads.com/search?q=Their+Eyes+Were+Watching+God"
 },
 {
   "state_long": "Louisiana",
   "state_short": "LA",
   "state_num": "18",
   "state_ratified_year": 1812,
   "title": "A Confederacy Of Dunces",
   "author": "John Kennedy Toole",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2468693",
   "img": "img/a_confederacy_of_dunces.jpg",
   "published": "1980",
   "pagecount": "418",
   "average_rating": "5",
   "description": "Set in New Orleans, the protagonist is nearly arrested for being a suspicious character and encounters many unfortunate events.",
   "url": "https://www.goodreads.com/search?q=A+Confederacy+Of+Dunces"
 },
 {
   "state_long": "Idaho",
   "state_short": "ID",
   "state_num": "43",
   "state_ratified_year": 1890,
   "title": "Housekeeping",
   "author": "Marilynne Robinson",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Housekeeping",
   "img": "img/housekeeping.jpg",
   "published": "1987",
   "pagecount": "228",
   "average_rating": "N/A",
   "description": "Ruth and her younger sister Lucille grow up haphazardly. The family house is in Fingerbone set on a glacial lake where their grandfather died in a spectacular train wreck, and their mother drove off a cliff to her death. Ruth and Lucille's struggle toward adulthood illuminates the price of loss and survival, and the dangerous and deep undertow of transience.",
   "url": "https://www.goodreads.com/search?q=Housekeeping"
 },
 {
   "state_long": "Ohio",
   "state_short": "OH",
   "state_num": "17",
   "state_ratified_year": 1803,
   "title": "Beloved",
   "author": "Toni Morrison",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Beloved",
   "img": "img/beloved.jpg",
   "published": "1988",
   "pagecount": "304",
   "average_rating": "4",
   "description": "WINNER OF THE NOBEL PRIZE IN LITERATURE.",
   "url": "https://www.goodreads.com/search?q=Beloved"
 },
 {
   "state_long": "Arizona",
   "state_short": "AZ",
   "state_num": "48",
   "state_ratified_year": 1912,
   "title": "Animal Dreams",
   "author": "Barbara Kingsolver",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4404474",
   "img": "img/animal_dreams.jpg",
   "published": "1990",
   "pagecount": "360",
   "average_rating": "N/A",
   "description": "Codi returns to her hometown to confront her past and face her ailing father. What she finds is a town threatened by an environmental catastrophe and a man who could change her life.",
   "url": "https://www.goodreads.com/search?q=Animal+Dreams"
 },
 {
   "state_long": "Texas",
   "state_short": "TX",
   "state_num": "28",
   "state_ratified_year": 1845,
   "title": "All The Pretty Horses",
   "author": "Cormac McCarthy",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4513670",
   "img": "img/all_the_pretty_horses.jpg",
   "published": "1992",
   "pagecount": "328",
   "average_rating": "4",
   "description": "John Grady Cole, 16, leaves Texas for Mexico in 1950 and becomes an essential vaquero in a hacienda's program.",
   "url": "https://www.goodreads.com/search?q=All+The+Pretty+Horses"
 },
 {
   "state_long": "Puerto Rico",
   "state_short": "PR",
   "state_num": "n/a",
   "state_ratified_year": 1952,
   "title": "When I Was Puerto Rican",
   "author": "Esmeralda Santiago",
   "audiobook_url": "",
   "img": "img/when_i_was_puerto_rican.jpg",
   "published": "1993",
   "pagecount": "274",
   "average_rating": "4",
   "description": "Esmeralda Santiago's story begins in rural Puerto Rico, where her childhood was full of both tenderness and domestic strife, tropical sounds and sights as well as poverty. When her mother, Mami, a force of nature, takes off to New York with her seven, soon to be eleven children, Esmeralda, the oldest, must learn new rules, a new language, and eventually take on a new identity.",
   "url": "https://www.goodreads.com/book/show/25419.When_I_Was_Puerto_Rican?ref=nav_sb_ss_1_23"
 },
 {
   "state_long": "Vermont",
   "state_short": "VT",
   "state_num": "14",
   "state_ratified_year": 1791,
   "title": "Midwives",
   "author": "Chris Bohjalian",
   "audiobook_url": "",
   "img": "img/midwives.jpg",
   "published": "1998",
   "pagecount": "388",
   "average_rating": "N/A",
   "description": "A cloth bag containing ten copies of the title, that may also include a folder with miscellaneous notes, discussion questions, biographical information, and reading lists to assist book group discussion leaders.",
   "url": "https://www.goodreads.com/search?q=Midwives"
 },
 {
   "state_long": "Tennessee",
   "state_short": "TN",
   "state_num": "16",
   "state_ratified_year": 1796,
   "title": "A Death In The Family",
   "author": "James Agee",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=A%20Death%20In%20The%20Family",
   "img": "img/a_death_in_the_family.jpg",
   "published": "1998",
   "pagecount": "322",
   "average_rating": "3",
   "description": "Sample Text",
   "url": "https://www.goodreads.com/search?q=A+Death+In+The+Family"
 },
 {
   "state_long": "Kentucky",
   "state_short": "KY",
   "state_num": "15",
   "state_ratified_year": 1792,
   "title": "Jayber Crow",
   "author": "Wendell Berry",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Jayber%20Crow",
   "img": "img/jayber_crow.jpg",
   "published": "2000",
   "pagecount": "394",
   "average_rating": "N/A",
   "description": "Jayber Crow finds purpose in his life as he works as a barber in a small community.",
   "url": "https://www.goodreads.com/search?q=Tabor+Crow"
 },
 {
   "state_long": "Mississippi",
   "state_short": "MS",
   "state_num": "20",
   "state_ratified_year": 1817,
   "title": "Roll Of Thunder Hear My Cry",
   "author": "Mildred D. Taylor",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2976943",
   "img": "img/roll_of_thunder_hear_my_cry.jpg",
   "published": "2001",
   "pagecount": "304",
   "average_rating": "4",
   "description": "A black family living in the South during the 1930's are faced with prejudice and discrimination which their children don't understand.",
   "url": "https://www.goodreads.com/search?q=Roll+Of+Thunder+Hear+My+Cry"
 },
 {
   "state_long": "Michigan",
   "state_short": "MI",
   "state_num": "26",
   "state_ratified_year": 1837,
   "title": "True North",
   "author": "Jim Harrison",
   "audiobook_url": "",
   "img": "img/true_north.jpg",
   "published": "2004",
   "pagecount": "404",
   "average_rating": "N/A",
   "description": "The author of Legends of the Fall presents a novel that revolves around David Burkett, a man who has grown up on Michigan's Upper Penninsula and realizes he must face the destruction caused to the region's natural environment by his ancestors. Reprint.. 35,000 first printing.",
   "url": "https://www.goodreads.com/search?q=True+North"
 },
 {
   "state_long": "Connecticut",
   "state_short": "CT",
   "state_num": "5",
   "state_ratified_year": 1788,
   "title": "Revolutionary Road",
   "author": "Richard Yates",
   "audiobook_url": "",
   "img": "img/revolutionary_road.jpg",
   "published": "2008",
   "pagecount": "355",
   "average_rating": "N/A",
   "description": "The devastating effects of work, adultery, rebellion, and self-deception slowly destroy the once successful marriage of Frank and April Wheeler, a suburban American couple. Reissue. 350,000 first printing. (A DreamWorks film, directed by Sam Mendes, releasing December 2008, starring Leonardo DiCaprio, Kate Winslet, Kathy Bates, David Harbour, Michael Shannon, & Zoe Kazan). (General Fiction)",
   "url": "https://www.goodreads.com/search?q=Revolutionary+Road"
 },
 {
   "state_long": "California",
   "state_short": "CA",
   "state_num": "31",
   "state_ratified_year": 1850,
   "title": "Play It As It Lays",
   "author": "Joan Didion",
   "audiobook_url": "",
   "img": "img/play_it_as_it_lays.jpg",
   "published": "2011",
   "pagecount": "N/A",
   "average_rating": "N/A",
   "description": "Somewhere out beyond Hollywood, has-been actress Maria Wyeth's life is going off the rails. But her permanent catatonic state leaves her a mere bystander to her own downward spiral. Observing her life with detachment, Wyeth epitomises a generation left lost and inert by too much freedom.",
   "url": "https://www.goodreads.com/search?q=Play+It+As+It+Lays"
 },
 {
   "state_long": "Minnesota",
   "state_short": "MN",
   "state_num": "32",
   "state_ratified_year": 1858,
   "title": "The Things They Carried",
   "author": "Tim O'Brien",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=The%20Things%20They%20Carried",
   "img": "img/the_things_they_carried.jpg",
   "published": "2011",
   "pagecount": "N/A",
   "average_rating": "N/A",
   "description": "A collection of interrelated stories by Tim O'Brien providing detailed accounts of the struggles faced by American soldiers on the ground during the Vietnam War. Written in no particular order, his narrative tells the stories of his many comrades during the war.",
   "url": "https://www.goodreads.com/search?q=The+Things+They+Carried"
 },
 {
   "state_long": "Alabama",
   "state_short": "AL",
   "state_num": "22",
   "state_ratified_year": 1819,
   "title": "Inside Out And Back Again",
   "author": "Thanhha Lai",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4537358",
   "img": "img/inside_out_and_back_again.jpg",
   "published": "2012",
   "pagecount": "262",
   "average_rating": "N/A",
   "description": "Moving to America turns H 's life inside out. H has only known Saigon- the thrills of its markets, the joy of its traditions, the warmth of her friends close by . . . and the beauty of her very own papaya tree. She and her family are forced to flee as Saigon falls, and they board a ship headed toward hope. In America, H discovers the foreign world of Alabama- the coldness of its strangers, the dullness of its food, the strange shape of its landscape . . . and the strength of her very own family.",
   "url": "https://www.goodreads.com/search?q=Inside+Out+And+Back+Again"
 },
 {
   "state_long": "American Samoa",
   "state_short": "WS",
   "state_num": "n/a",
   "state_ratified_year": 1899,
   "title": "Leaves of the Banyan Tree",
   "author": "Albert Wendt",
   "audiobook_url": "",
   "img": "img/leaves_of_the_banyan_tree.jpg",
   "published": "January 1, 1979",
   "pagecount": "424",
   "average_rating": "3.98",
   "description": "A rich narrative set in American Samoa, intertwining family dynamics with the cultural significance of the banyan tree.",
   "url": "https://www.goodreads.com/book/show/368553.Leaves_of_the_Banyan_Tree"
 },
 {
   "state_long": "Kansas",
   "state_short": "KS",
   "state_num": "34",
   "state_ratified_year": 1861,
   "title": "The Wonderful Wizard of Oz",
   "author": "L. Frank Baum",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2747205",
   "img": "img/the_wonderful_wizard_of_oz.jpg",
   "published": "1993-04-15",
   "pagecount": "196",
   "average_rating": "3",
   "description": "After a cyclone transports her to the land of Oz, Dorothy must seek out the great wizard in order to return to Kansas.",
   "url": "https://www.goodreads.com/book/show/236093.The_Wonderful_Wizard_of_Oz?ref=nav_sb_ss_1_26"
 },
 {
   "state_long": "Wyoming",
   "state_short": "WY",
   "state_num": "44",
   "state_ratified_year": 1890,
   "title": "Close Range",
   "author": "Annie Proulx",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2468056",
   "img": "img/close_range.jpg",
   "published": "2000-02-10",
   "pagecount": "288",
   "average_rating": "N/A",
   "description": "Breathtaking tales of loneliness, quick violence, and the wrong kinds of love. Each of the stunning portraits in Close Range reveals characters fiercely wrought with precision and grace. These are stories of desperation and unlikely elation, set in a landscape both stark and magnificent -- by an author writing at the peak of her craft.",
   "url": "https://www.goodreads.com/search?q=Close+Range"
 },
 {
   "state_long": "Colorado",
   "state_short": "CO",
   "state_num": "38",
   "state_ratified_year": 1876,
   "title": "The Shining",
   "author": "Stephen King",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2568719",
   "img": "img/the_shining.jpg",
   "published": "2002-10",
   "pagecount": "530",
   "average_rating": "4",
   "description": "Jack Torrance becomes winter caretaker at the isolated Overlook Hotel in Colorado. His son Danny is plagued by psychic premonitions. As Danny's visions become more disturbing, Jack discovers the hotel's dark secrets and begins to unravel into a homicidal maniac hell-bent on terrorizing his family.",
   "url": "https://www.goodreads.com/search?q=The+Shining"
 },
 {
   "state_long": "Virginia",
   "state_short": "VA",
   "state_num": "10",
   "state_ratified_year": 1788,
   "title": "The Known World",
   "author": "Edward P. Jones",
   "audiobook_url": "",
   "img": "img/the_known_world.jpg",
   "published": "2004-06-15",
   "pagecount": "580",
   "average_rating": "3.5",
   "description": "In this acclaimed novel, Edward P. Jones tells the story of Henry Townsend, a black farmer and former slave who falls under the tutelage of William Robbins, the most powerful man in Manchester County, Virginia. Making certain he never circumvents the law, Townsend runs his affairs with unusual discipline. But when death takes him unexpectedly, his widow, Caldonia, can't uphold the estate's order and chaos ensues.",
   "url": "https://www.goodreads.com/search?q=The+Known+World"
 },
 {
   "state_long": "Georgia",
   "state_short": "GA",
   "state_num": "4",
   "state_ratified_year": 1788,
   "title": "Gone With The Wind",
   "author": "Margaret Mitchell",
   "audiobook_url": "",
   "img": "img/gone_with_the_wind.jpg",
   "published": "2008-05-20",
   "pagecount": "1476",
   "average_rating": "4.5",
   "description": "The story of the tempestuous romance between Rhett Butler and Scarlet O'Hara is set amid the drama of the Civil War.",
   "url": "https://www.goodreads.com/search?q=Gone+With+The+Wind"
 },
 {
   "state_long": "Virgin Islands",
   "state_short": "VI",
   "state_num": "n/a",
   "state_ratified_year": 1917,
   "title": "Land of Love and Drowning",
   "author": "Tiphanie Yanique",
   "audiobook_url": "",
   "img": "img/land_of_love_and_drowning.jpg",
   "published": "July 10, 2014",
   "pagecount": "358",
   "average_rating": "3.37",
   "description": "When an important ship sinks into the Caribbean Sea, two sisters and their half brother are orphaned and now face an uncertain identity and future. Chronicling three generations of an island family from 1916 to the 1970s, Land of Love and Drowning is a novel of love and magic, set against the emergence of Saint Thomas into the modern world.",
   "url": "https://www.goodreads.com/book/show/18693616-land-of-love-and-drowning?from_search=true&from_srp=true&qid=FSlnmd3FTz&rank=1"
 },
 {
   "state_long": "Maine",
   "state_short": "ME",
   "state_num": "23",
   "state_ratified_year": 1820,
   "title": "Olive Kittredge",
   "author": "Elizabeth Strout",
   "audiobook_url": "",
   "img": "img/olive_kittredge.jpg",
   "published": "2014-12-04",
   "pagecount": "N/A",
   "average_rating": "N/A",
   "description": "A retired schoolteacher in a small coastal town in Maine struggles to make sense of the changes in her life. A penetrating, vibrant exploration of the human soul, the story of Olive Kitteridge will make you laugh, nod in recognition, wince in pain, and shed a tear or two.",
   "url": "https://www.goodreads.com/search?q=Olive+Kittredge"
 },
 {
   "state_long": "Delaware",
   "state_short": "DE",
   "state_num": "1",
   "state_ratified_year": 1787,
   "title": "The Book Of Unknown Americas",
   "author": "Cristina Henríquez",
   "audiobook_url": "",
   "img": "img/the_book_of_unknown_americas.jpg",
   "published": "2019-05-02",
   "pagecount": "N/A",
   "average_rating": "N/A",
   "description": "A deeply moving novel about the many different voices of the immigrant experience, inspired by the story of the author's father.",
   "url": "https://www.goodreads.com/search?q=The+Book+Of+Unknown+Americas"
 },
 {
   "state_long": "New Jersey",
   "state_short": "NJ",
   "state_num": "3",
   "state_ratified_year": 1787,
   "title": "Election",
   "author": "Tom Perrotta",
   "audiobook_url": "",
   "img": "img/election.jpg",
   "published": "1998",
   "pagecount": "",
   "average_rating": "",
   "description": "A brilliantly funny novel from the author of ‘The Abstinence Teacher’ and ‘Little Children’, made into an acclaimed film starring Reece Witherspoon and Matthew Broderick.",
   "url": "https://www.goodreads.com/search?q=Election"
 },
 {
   "state_long": "Hawaii",
   "state_short": "HI",
   "state_num": "50",
   "state_ratified_year": 1959,
   "title": "Malachi",
   "author": "Alan Brennert",
   "audiobook_url": "",
   "img": "img/malachi.jpg",
   "published": "1981",
   "pagecount": "",
   "average_rating": "",
   "description": "A captivating story set in Hawaii, weaving together the lives of its characters against the backdrop of the islands' unique culture.",
   "url": "https://www.goodreads.com/search?q=Malachi"
 },
 {
   "state_long": "Illinois",
   "state_short": "IL",
   "state_num": "21",
   "state_ratified_year": 1818,
   "title": "The House On Mango St.",
   "author": "Sandra Cisneros",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=The%20House%20On%20Mango%20St.",
   "img": "img/the_house_on_mango_st..jpg",
   "published": "1984",
   "pagecount": "",
   "average_rating": "",
   "description": "A coming-of-age novel set in Chicago, offering a vivid portrayal of a young Latina girl's experiences and dreams.",
   "url": "https://www.goodreads.com/search?q=The+House+On+Mango+St."
 },
 {
   "state_long": "Alaska",
   "state_short": "AK",
   "state_num": "49",
   "state_ratified_year": 1959,
   "title": "To The Bright Edge Of The World",
   "author": "Greene Bette",
   "audiobook_url": "https://www.hoopladigital.com/title/13524386?utm_source=MARC",
   "img": "img/to_the_bright_edge_of_the_world.jpg",
   "published": "2016",
   "pagecount": "",
   "average_rating": "",
   "description": "A compelling adventure that explores the uncharted territories of Alaska, taking readers to the bright edge of the world.",
   "url": "https://www.goodreads.com/search?q=Summer+Of+My+German+Soldier"
 },
 {
   "state_long": "Maryland",
   "state_short": "MD",
   "state_num": "7",
   "state_ratified_year": 1788,
   "title": "The Accidental Tourist",
   "author": "Anne Tyler",
   "audiobook_url": "",
   "img": "img/the_accidental_tourist.jpg",
   "published": "1985",
   "pagecount": "",
   "average_rating": "",
   "description": "A heartwarming and humorous story set in Maryland, exploring love, loss, and the unexpected turns life can take.",
   "url": "https://www.goodreads.com/search?q=The+Accidental+Tourist"
 },
 {
   "state_long": "Massachusetts",
   "state_short": "MA",
   "state_num": "6",
   "state_ratified_year": 1788,
   "title": "Townie",
   "author": "Andre Dubus",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Townie",
   "img": "img/townie.jpg",
   "published": "2011",
   "pagecount": "",
   "average_rating": "",
   "description": "A memoir set in Massachusetts, Townie recounts the author's journey from a violent childhood to finding his way as a writer.",
   "url": "https://www.goodreads.com/book/show/8248617-townie?ref=nav_sb_ss_1_6"
 },
 {
   "state_long": "Iowa",
   "state_short": "IA",
   "state_num": "29",
   "state_ratified_year": 1846,
   "title": "1000 Acres",
   "author": "Jane Smiley",
   "audiobook_url": "",
   "img": "img/1000_acres.jpg",
   "published": "1991",
   "pagecount": "",
   "average_rating": "",
   "description": "A modern adaptation of Shakespeare's \"King Lear,\" delving into family relationships and the complexities of rural life in Iowa.",
   "url": "https://www.goodreads.com/search?q=1000+Acres"
 },
 {
   "state_long": "Arkansas",
   "state_short": "AR",
   "state_num": "25",
   "state_ratified_year": 1836,
   "title": "Summer Of My German Soldier",
   "author": "Eowyn Ivey",
   "audiobook_url": "",
   "img": "img/summer_of_my_german_soldier.jpg",
   "published": "1973",
   "pagecount": "",
   "average_rating": "",
   "description": "A poignant tale set in Arkansas during World War II, exploring the complexities of human connections and wartime challenges.",
   "url": "https://www.goodreads.com/search?q=To+The+Bright+Edge+Of+The+World"
 },
 {
   "state_long": "California",
   "state_short": "CA",
   "state_num": "31",
   "state_ratified_year": 1850,
   "title": "Drop City",
   "author": "T. C. Boyle",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2245143",
   "img": "img/drop_city.jpg",
   "published": "2003",
   "pagecount": "",
   "average_rating": "",
   "description": "An exploration of counterculture and societal norms in 1970s California, where a commune called Drop City takes center stage.",
   "url": "https://www.goodreads.com/search?q=Drop+City"
 },
 {
   "state_long": "Indiana",
   "state_short": "IN",
   "state_num": "19",
   "state_ratified_year": 1816,
   "title": "The Stone Diaries",
   "author": "Carol Shields",
   "audiobook_url": "",
   "img": "img/the_stone_diaries.jpg",
   "published": "1993",
   "pagecount": "",
   "average_rating": "",
   "description": "An introspective journey through the life of Daisy Goodwill Flett, set against the backdrop of early 20th-century Indiana.",
   "url": "https://www.goodreads.com/search?q=The+Stone+Diaries"
 },
 {
   "state_long": "Texas",
   "state_short": "TX",
   "state_num": "28",
   "state_ratified_year": 1845,
   "title": "Lonesome Dove",
   "author": "Larry McMurtry",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C5091312",
   "img": "img/lonesome_dove.jpg",
   "published": "1985",
   "pagecount": "",
   "average_rating": "",
   "description": "It is an epic of love, heroism, loyalty, honor, and betrayal -- faultlessly written, unfailingly dramatic. Lonesome Dove is the novel about the West that American literature -- and the American reader -- has long been waiting for.",
   "url": "https://www.goodreads.com/search?q=Lonesome+Dove"
 },
 {
   "state_long": "Nebraska",
   "state_short": "NE",
   "state_num": "37",
   "state_ratified_year": 1867,
   "title": "Me Antonia",
   "author": "Willa Cather",
   "audiobook_url": "",
   "img": "img/me_antonia.jpg",
   "published": "1918",
   "pagecount": "",
   "average_rating": "",
   "description": "Young Jim Burden is an orphan sent to live with his grandparents in Black Hawk, Nebraska. He befriends the neighboring Shimerda family, Romanian immigrants seeking the American Dream on the frontier.",
   "url": "https://www.goodreads.com/search?q=Me+Antonia"
 },
 {
   "state_long": "Missouri",
   "state_short": "MO",
   "state_num": "24",
   "state_ratified_year": 1821,
   "title": "Winter’s Bone",
   "author": "Daniel Woodrell",
   "audiobook_url": "",
   "img": "img/winter’s_bone.jpg",
   "published": "2006",
   "pagecount": "",
   "average_rating": "",
   "description": "Description: A gripping tale set in the Ozarks, where a young girl navigates the dangerous criminal underworld to find her missing father.",
   "url": "https://www.goodreads.com/search?q=Winter’s+Bone"
 },
 {
   "state_long": "Montana",
   "state_short": "MT",
   "state_num": "41",
   "state_ratified_year": 1889,
   "title": "Breaking Clean",
   "author": "Judy J. Blunt",
   "audiobook_url": "",
   "img": "img/breaking_clean.jpg",
   "published": "2002",
   "pagecount": "",
   "average_rating": "",
   "description": "An honest and moving memoir depicting the challenges and triumphs of a woman breaking free from the constraints of ranch life in Montana.",
   "url": "https://www.goodreads.com/search?q=Breaking+Clean"
 },
 {
   "state_long": "Nevada",
   "state_short": "NV",
   "state_num": "36",
   "state_ratified_year": 1864,
   "title": "Grind",
   "author": "Mark Maynard",
   "audiobook_url": "No",
   "img": "img/grind.jpg",
   "published": "2005",
   "pagecount": "",
   "average_rating": "",
   "description": "A vivid exploration of life in the desert, blending elements of adventure and self-discovery against the backdrop of Nevada's unique landscape.",
   "url": "https://www.goodreads.com/search?q=Grind"
 },
 {
   "state_long": "New Hampshire",
   "state_short": "NH",
   "state_num": "9",
   "state_ratified_year": 1788,
   "title": "Hotel New Hampshire",
   "author": "John Irving",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Hotel%20New%20Hampshire",
   "img": "img/hotel_new_hampshire.jpg",
   "published": "1981",
   "pagecount": "",
   "average_rating": "",
   "description": "A quirky and heartwarming family saga that unfolds in the eccentric world of the Hotel New Hampshire.",
   "url": "https://www.goodreads.com/search?q=H2hotel+New+Hampshire"
 },
 {
   "state_long": "New Mexico",
   "state_short": "NM",
   "state_num": "47",
   "state_ratified_year": 1912,
   "title": "Ceremony",
   "author": "Leslie Marmon Silko",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4533922",
   "img": "img/ceremony.jpg",
   "published": "1977",
   "pagecount": "",
   "average_rating": "",
   "description": "A profound novel exploring the cultural and spiritual challenges faced by a Laguna Pueblo man returning from World War II.",
   "url": "https://www.goodreads.com/search?q=Ceremony"
 },
 {
   "state_long": "New York",
   "state_short": "NY",
   "state_num": "11",
   "state_ratified_year": 1788,
   "title": "The Bonfire Of The Vanities",
   "author": "Tom Wolfe",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C3580821",
   "img": "img/the_bonfire_of_the_vanities.jpg",
   "published": "1987",
   "pagecount": "",
   "average_rating": "",
   "description": "A satirical masterpiece that dissects the excesses and moral decay of 1980s New York City.",
   "url": "https://www.goodreads.com/search?q=The+Bonfire+Of+The+Vanities"
 },
 {
   "state_long": "North Carolina",
   "state_short": "NC",
   "state_num": "12",
   "state_ratified_year": 1789,
   "title": "A Short History Of A Small Place",
   "author": "T. R. Pearson",
   "audiobook_url": "",
   "img": "img/a_short_history_of_a_small_place.jpg",
   "published": "1985",
   "pagecount": "",
   "average_rating": "",
   "description": "A charming and humorous portrayal of small-town life in North Carolina, filled with eccentric characters and delightful anecdotes.",
   "url": "https://www.goodreads.com/search?q=A+Short+History+Of+A+Small+Place"
 },
 {
   "state_long": "North Dakota",
   "state_short": "ND",
   "state_num": "39",
   "state_ratified_year": 1889,
   "title": "Love Medicine",
   "author": "Louise Erdrich",
   "audiobook_url": "",
   "img": "img/love_medicine.jpg",
   "published": "1984",
   "pagecount": "",
   "average_rating": "",
   "description": "Interconnected stories capturing the lives and struggles of a Native American community in North Dakota.",
   "url": "https://www.goodreads.com/search?q=Love+Medicine"
 },
 {
   "state_long": "Oregon",
   "state_short": "OR",
   "state_num": "33",
   "state_ratified_year": 1859,
   "title": "Geek Love",
   "author": "Katherine Dunn",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=Geek%20Love",
   "img": "img/geek_love.jpg",
   "published": "1989",
   "pagecount": "",
   "average_rating": "",
   "description": "A dark and unconventional tale that explores the eccentricities of a family with intentionally induced deformities.",
   "url": "https://www.goodreads.com/search?q=Geek+Love"
 },
 {
   "state_long": "Rhode Island",
   "state_short": "RI",
   "state_num": "13",
   "state_ratified_year": 1790,
   "title": "The Marriage Plot",
   "author": "Jeffrey Eugenides",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C2528836",
   "img": "img/the_marriage_plot.jpg",
   "published": "2011",
   "pagecount": "",
   "average_rating": "",
   "description": "A thought-provoking exploration of love, literature, and identity, set against the backdrop of academia in Rhode Island.",
   "url": "https://www.goodreads.com/search?q=The+Marriage+Plot"
 },
 {
   "state_long": "South Carolina",
   "state_short": "SC",
   "state_num": "8",
   "state_ratified_year": 1788,
   "title": "The Prince Of Tides",
   "author": "Pat Conroy",
   "audiobook_url": "",
   "img": "img/the_prince_of_tides.jpg",
   "published": "1986",
   "pagecount": "",
   "average_rating": "",
   "description": "A rich and emotionally charged novel delving into family secrets and the complexities of identity in the low country of South Carolina.",
   "url": "https://www.goodreads.com/search?q=The+Prince+Of+Tides"
 },
 {
   "state_long": "South Dakota",
   "state_short": "SD",
   "state_num": "40",
   "state_ratified_year": 1889,
   "title": "By The Shores Of Silverlake",
   "author": "Laura Ingalls Wilder",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=By%20The%20Shores%20Of%20Silverlake",
   "img": "img/by_the_shores_of_silverlake.jpg",
   "published": "1939",
   "pagecount": "",
   "average_rating": "",
   "description": "A classic installment in the \"Little House\" series, following the adventures of Laura Ingalls Wilder in the Dakota Territory.",
   "url": "https://www.goodreads.com/search?q=By+The+Shores+Of+Silverlake"
 },
 {
   "state_long": "Utah",
   "state_short": "UT",
   "state_num": "45",
   "state_ratified_year": 1896,
   "title": "The Lonely Polygamist",
   "author": "Brady Udall",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4544193",
   "img": "img/the_lonely_polygamist.jpg",
   "published": "2010",
   "pagecount": "",
   "average_rating": "",
   "description": "A humorous and poignant exploration of the challenges faced by a polygamist in a modern world, set in the landscapes of Utah.",
   "url": "https://www.goodreads.com/search?q=The+Lonely+Polygamist"
 },
 {
   "state_long": "Washington",
   "state_short": "WA",
   "state_num": "42",
   "state_ratified_year": 1889,
   "title": "Another Roadside Attraction",
   "author": "Tom Robbins",
   "audiobook_url": "",
   "img": "img/another_roadside_attraction.jpg",
   "published": "1971",
   "pagecount": "",
   "average_rating": "",
   "description": "A whimsical and surreal tale of love, philosophy, and the extraordinary adventures of a couple running a roadside zoo in Washington.",
   "url": "https://www.goodreads.com/search?q=Another+Roadside+Attraction"
 },
 {
   "state_long": "West Virginia",
   "state_short": "WV",
   "state_num": "35",
   "state_ratified_year": 1863,
   "title": "John Henry Days",
   "author": "Colson Whitehead",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/record/S93C4537606",
   "img": "img/john_henry_days.jpg",
   "published": "2001",
   "pagecount": "",
   "average_rating": "",
   "description": "A novel that weaves together historical and contemporary threads, exploring the legacy of John Henry, the legendary steel-driving man, in West Virginia.",
   "url": "https://www.goodreads.com/search?q=John+Henry+Days"
 },
 {
   "state_long": "Wisconsin",
   "state_short": "WI",
   "state_num": "30",
   "state_ratified_year": 1848,
   "title": "American Gods",
   "author": "Neil Gaiman",
   "audiobook_url": "https://sfpl.bibliocommons.com/v2/search?query=American%20Gods",
   "img": "img/american_gods.jpg",
   "published": "2001",
   "pagecount": "",
   "average_rating": "",
   "description": "A captivating fantasy novel that blends mythology, gods, and the American landscape, taking readers on a unique and magical journey.",
   "url": "https://www.goodreads.com/search?q=American+Gods"
 }
]